services:

 caddy:
    image: caddy:latest
    container_name: caddy
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    environment:
      - ACME_AGREE=true
      - EMAIL=example@mail.com
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    networks:
      - caddy
      
  backend:
    container_name: backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    environment:
      - PORT=3001
    networks:
      - caddy
    volumes:
      - db:/app/db
    restart: unless-stopped

  homepage:
    container_name: homepage
    build:
      context: ./website/homepage
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    networks:
      - caddy
    restart: unless-stopped

  dashboard:
    container_name: dashboard
    build:
      context: ./dashboard
      dockerfile: Dockerfile
    environment:
      - API_URL=http://localhost:3001/api
    ports:
      - "3002:3000"
    networks:
      - caddy
    restart: unless-stopped

volumes:
  db:
  caddy_data:
  caddy_config:
networks:
  caddy:
    external: true
