name: Docker Image CI

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
          - uses: actions/checkout@v4
          - name: Login to Docker Hub
            uses: docker/login-action@v3
            with:
              username: ${{ secrets.DOCKERHUB_USERNAME }}
              password: ${{ secrets.DOCKERHUB_TOKEN }}
          - name: Build the Docker image
            working-directory: website
            run: docker build -t samvandenabeele09/novacan:pr-latest .
          - name: Push new docker image
            working-directory: website
            run: docker push samvandenabeele09/novacan:pr-latest
          - name: logout from Docker Hub
            run: docker logout